# Generated by Django 3.1.7 on 2021-07-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_predmeta', models.CharField(max_length=30)),
                ('broj_ectsa', models.IntegerField()),
                ('semestar_predmeta', models.IntegerField()),
                ('obavezan_predmet', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('redovan_student', models.BooleanField()),
                ('broj_ostvarenih_ectsa', models.IntegerField()),
                ('semestar_studija', models.IntegerField()),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.predmet')),
            ],
        ),
        migrations.AddField(
            model_name='predmet',
            name='nositelj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.profesor'),
        ),
    ]
