# Generated by Django 3.1.7 on 2021-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210706_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='redovan_student',
            field=models.BooleanField(default=True),
        ),
    ]
