# Generated by Django 3.1.7 on 2021-07-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210706_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='predmet_id',
            field=models.CharField(default=762, max_length=10, unique=True),
        ),
    ]
