# Generated by Django 3.1.7 on 2021-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210706_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='predmet',
        ),
        migrations.AlterField(
            model_name='predmet',
            name='predmet_id',
            field=models.CharField(default=7901, max_length=10, null=True, unique=True),
        ),
    ]
