# Generated by Django 3.1.7 on 2021-07-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210706_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='predmet_id',
            field=models.CharField(default=6980, max_length=10, null=True, unique=True),
        ),
    ]
