# Generated by Django 3.1.7 on 2021-07-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210707_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='predmet_id',
            field=models.CharField(default=5287, max_length=10, null=True, unique=True),
        ),
    ]
