# Generated by Django 2.2.12 on 2021-07-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210707_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='predmet_id',
            field=models.CharField(default=5350, max_length=10, null=True, unique=True),
        ),
    ]
