# Generated by Django 2.2.12 on 2021-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210709_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='predmet_id',
            field=models.CharField(default=5820, max_length=10, null=True, unique=True),
        ),
    ]
