# Generated by Django 2.2.12 on 2021-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210709_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmet',
            name='predmet_id',
        ),
        migrations.AddField(
            model_name='student',
            name='broj_xice',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='predmet',
            field=models.ManyToManyField(to='main.Predmet'),
        ),
    ]
