# Generated by Django 2.2.12 on 2021-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210709_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semestar_studija',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
