# Generated by Django 2.2.12 on 2021-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210711_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polozeni_Predmeti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_predmeta', models.CharField(max_length=30)),
                ('broj_ectsa', models.IntegerField(default=5)),
                ('semestar_predmeta', models.IntegerField()),
                ('obavezan_predmet', models.BooleanField()),
                ('polozen', models.BooleanField()),
                ('nositelj_predmeta', models.ManyToManyField(to='main.Profesor')),
            ],
        ),
    ]
