# Generated by Django 2.2.12 on 2021-07-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_polozeni_predmeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='polozeni_predmeti',
            field=models.ManyToManyField(to='main.Polozeni_Predmeti'),
        ),
    ]
