# Generated by Django 2.2.12 on 2021-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_student_polozeni_predmeti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti_druge_godine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_predmeta', models.CharField(max_length=30)),
                ('broj_ectsa', models.IntegerField(default=5)),
                ('semestar_predmeta', models.IntegerField()),
                ('obavezan_predmet', models.BooleanField()),
                ('nositelj_predmeta', models.ManyToManyField(to='main.Profesor')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='polozeni_predmeti',
            field=models.ManyToManyField(to='main.Predmeti_druge_godine'),
        ),
        migrations.DeleteModel(
            name='Polozeni_Predmeti',
        ),
    ]
